/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Asset = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'interestRate' : IDL.Float64,
  'priceUSD' : IDL.Float64,
  'liquidationThreshold' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const PositionType = IDL.Variant({
  'borrow' : IDL.Null,
  'deposit' : IDL.Null,
});
export const PortfolioTotals = IDL.Record({
  'netValue' : IDL.Float64,
  'healthFactor' : IDL.Float64,
  'liquidationPrice' : IDL.Float64,
  'totalBorrows' : IDL.Float64,
  'totalDeposits' : IDL.Float64,
});
export const Time = IDL.Int;
export const Position = IDL.Record({
  'id' : IDL.Nat,
  'asset' : Asset,
  'createdAt' : Time,
  'positionType' : PositionType,
  'amount' : IDL.Float64,
});
export const EducationalGuidance = IDL.Record({
  'parameterSuggestions' : IDL.Text,
  'riskAnalysis' : IDL.Text,
  'learningResources' : IDL.Vec(IDL.Text),
});
export const Protocol = IDL.Variant({
  'aave' : IDL.Null,
  'compound' : IDL.Null,
});
export const MarketDataSource = IDL.Record({
  'protocol' : Protocol,
  'isLive' : IDL.Bool,
});
export const RiskMetrics = IDL.Record({
  'collateralRatio' : IDL.Float64,
  'healthFactor' : IDL.Float64,
  'priceSensitivity' : IDL.Float64,
  'liquidationThreshold' : IDL.Float64,
});
export const ScenarioStep = IDL.Record({
  'timestamp' : Time,
  'priceChangePct' : IDL.Float64,
  'interestAccrued' : IDL.Float64,
});
export const YieldMetrics = IDL.Record({
  'apr' : IDL.Float64,
  'apy' : IDL.Float64,
  'depositInterest' : IDL.Float64,
  'borrowInterest' : IDL.Float64,
  'netYield' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addPosition' : IDL.Func([Asset, PositionType, IDL.Float64], [], []),
  'addScenarioStep' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'getAggregatedPortfolio' : IDL.Func([], [PortfolioTotals], ['query']),
  'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getEducationalGuidance' : IDL.Func([], [EducationalGuidance], ['query']),
  'getMarketDataSource' : IDL.Func([], [MarketDataSource], ['query']),
  'getRiskMetrics' : IDL.Func([], [RiskMetrics], ['query']),
  'getScenarioHistory' : IDL.Func([], [IDL.Vec(ScenarioStep)], ['query']),
  'getYieldMetrics' : IDL.Func([], [YieldMetrics], ['query']),
  'setMarketDataSource' : IDL.Func([MarketDataSource], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Asset = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'interestRate' : IDL.Float64,
    'priceUSD' : IDL.Float64,
    'liquidationThreshold' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const PositionType = IDL.Variant({
    'borrow' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const PortfolioTotals = IDL.Record({
    'netValue' : IDL.Float64,
    'healthFactor' : IDL.Float64,
    'liquidationPrice' : IDL.Float64,
    'totalBorrows' : IDL.Float64,
    'totalDeposits' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Position = IDL.Record({
    'id' : IDL.Nat,
    'asset' : Asset,
    'createdAt' : Time,
    'positionType' : PositionType,
    'amount' : IDL.Float64,
  });
  const EducationalGuidance = IDL.Record({
    'parameterSuggestions' : IDL.Text,
    'riskAnalysis' : IDL.Text,
    'learningResources' : IDL.Vec(IDL.Text),
  });
  const Protocol = IDL.Variant({ 'aave' : IDL.Null, 'compound' : IDL.Null });
  const MarketDataSource = IDL.Record({
    'protocol' : Protocol,
    'isLive' : IDL.Bool,
  });
  const RiskMetrics = IDL.Record({
    'collateralRatio' : IDL.Float64,
    'healthFactor' : IDL.Float64,
    'priceSensitivity' : IDL.Float64,
    'liquidationThreshold' : IDL.Float64,
  });
  const ScenarioStep = IDL.Record({
    'timestamp' : Time,
    'priceChangePct' : IDL.Float64,
    'interestAccrued' : IDL.Float64,
  });
  const YieldMetrics = IDL.Record({
    'apr' : IDL.Float64,
    'apy' : IDL.Float64,
    'depositInterest' : IDL.Float64,
    'borrowInterest' : IDL.Float64,
    'netYield' : IDL.Float64,
  });
  
  return IDL.Service({
    'addPosition' : IDL.Func([Asset, PositionType, IDL.Float64], [], []),
    'addScenarioStep' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'getAggregatedPortfolio' : IDL.Func([], [PortfolioTotals], ['query']),
    'getAllPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getEducationalGuidance' : IDL.Func([], [EducationalGuidance], ['query']),
    'getMarketDataSource' : IDL.Func([], [MarketDataSource], ['query']),
    'getRiskMetrics' : IDL.Func([], [RiskMetrics], ['query']),
    'getScenarioHistory' : IDL.Func([], [IDL.Vec(ScenarioStep)], ['query']),
    'getYieldMetrics' : IDL.Func([], [YieldMetrics], ['query']),
    'setMarketDataSource' : IDL.Func([MarketDataSource], [], []),
  });
};

export const init = ({ IDL }) => { return []; };