/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : string,
  'name' : string,
  'interestRate' : number,
  'priceUSD' : number,
  'liquidationThreshold' : number,
  'symbol' : string,
}
export interface EducationalGuidance {
  'parameterSuggestions' : string,
  'riskAnalysis' : string,
  'learningResources' : Array<string>,
}
export interface MarketDataSource { 'protocol' : Protocol, 'isLive' : boolean }
export interface PortfolioTotals {
  'netValue' : number,
  'healthFactor' : number,
  'liquidationPrice' : number,
  'totalBorrows' : number,
  'totalDeposits' : number,
}
export interface Position {
  'id' : bigint,
  'asset' : Asset,
  'createdAt' : Time,
  'positionType' : PositionType,
  'amount' : number,
}
export type PositionType = { 'borrow' : null } |
  { 'deposit' : null };
export type Protocol = { 'aave' : null } |
  { 'compound' : null };
export interface RiskMetrics {
  'collateralRatio' : number,
  'healthFactor' : number,
  'priceSensitivity' : number,
  'liquidationThreshold' : number,
}
export interface ScenarioStep {
  'timestamp' : Time,
  'priceChangePct' : number,
  'interestAccrued' : number,
}
export type Time = bigint;
export interface YieldMetrics {
  'apr' : number,
  'apy' : number,
  'depositInterest' : number,
  'borrowInterest' : number,
  'netYield' : number,
}
export interface _SERVICE {
  'addPosition' : ActorMethod<[Asset, PositionType, number], undefined>,
  'addScenarioStep' : ActorMethod<[number, number], undefined>,
  'getAggregatedPortfolio' : ActorMethod<[], PortfolioTotals>,
  'getAllPositions' : ActorMethod<[], Array<Position>>,
  'getEducationalGuidance' : ActorMethod<[], EducationalGuidance>,
  'getMarketDataSource' : ActorMethod<[], MarketDataSource>,
  'getRiskMetrics' : ActorMethod<[], RiskMetrics>,
  'getScenarioHistory' : ActorMethod<[], Array<ScenarioStep>>,
  'getYieldMetrics' : ActorMethod<[], YieldMetrics>,
  'setMarketDataSource' : ActorMethod<[MarketDataSource], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];