/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Position {
    id: bigint;
    asset: Asset;
    createdAt: Time;
    positionType: PositionType;
    amount: number;
}
export type Time = bigint;
export interface ScenarioStep {
    timestamp: Time;
    priceChangePct: number;
    interestAccrued: number;
}
export interface EducationalGuidance {
    parameterSuggestions: string;
    riskAnalysis: string;
    learningResources: Array<string>;
}
export interface RiskMetrics {
    collateralRatio: number;
    healthFactor: number;
    priceSensitivity: number;
    liquidationThreshold: number;
}
export interface Asset {
    id: string;
    name: string;
    interestRate: number;
    priceUSD: number;
    liquidationThreshold: number;
    symbol: string;
}
export interface YieldMetrics {
    apr: number;
    apy: number;
    depositInterest: number;
    borrowInterest: number;
    netYield: number;
}
export interface MarketDataSource {
    protocol: Protocol;
    isLive: boolean;
}
export interface PortfolioTotals {
    netValue: number;
    healthFactor: number;
    liquidationPrice: number;
    totalBorrows: number;
    totalDeposits: number;
}
export enum PositionType {
    borrow = "borrow",
    deposit = "deposit"
}
export enum Protocol {
    aave = "aave",
    compound = "compound"
}
export interface backendInterface {
    addPosition(asset: Asset, positionType: PositionType, amount: number): Promise<void>;
    addScenarioStep(priceChangePct: number, interestAccrued: number): Promise<void>;
    getAggregatedPortfolio(): Promise<PortfolioTotals>;
    getAllPositions(): Promise<Array<Position>>;
    getEducationalGuidance(): Promise<EducationalGuidance>;
    getMarketDataSource(): Promise<MarketDataSource>;
    getRiskMetrics(): Promise<RiskMetrics>;
    getScenarioHistory(): Promise<Array<ScenarioStep>>;
    getYieldMetrics(): Promise<YieldMetrics>;
    setMarketDataSource(source: MarketDataSource): Promise<void>;
}
import type { Asset as _Asset, MarketDataSource as _MarketDataSource, Position as _Position, PositionType as _PositionType, Protocol as _Protocol, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPosition(arg0: Asset, arg1: PositionType, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPosition(arg0, to_candid_PositionType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPosition(arg0, to_candid_PositionType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addScenarioStep(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addScenarioStep(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScenarioStep(arg0, arg1);
            return result;
        }
    }
    async getAggregatedPortfolio(): Promise<PortfolioTotals> {
        if (this.processError) {
            try {
                const result = await this.actor.getAggregatedPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAggregatedPortfolio();
            return result;
        }
    }
    async getAllPositions(): Promise<Array<Position>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPositions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPositions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEducationalGuidance(): Promise<EducationalGuidance> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducationalGuidance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducationalGuidance();
            return result;
        }
    }
    async getMarketDataSource(): Promise<MarketDataSource> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketDataSource();
                return from_candid_MarketDataSource_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketDataSource();
            return from_candid_MarketDataSource_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskMetrics(): Promise<RiskMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskMetrics();
            return result;
        }
    }
    async getScenarioHistory(): Promise<Array<ScenarioStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScenarioHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScenarioHistory();
            return result;
        }
    }
    async getYieldMetrics(): Promise<YieldMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getYieldMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYieldMetrics();
            return result;
        }
    }
    async setMarketDataSource(arg0: MarketDataSource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMarketDataSource(to_candid_MarketDataSource_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMarketDataSource(to_candid_MarketDataSource_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_MarketDataSource_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketDataSource): MarketDataSource {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PositionType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionType): PositionType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Protocol_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Protocol): Protocol {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    asset: _Asset;
    createdAt: _Time;
    positionType: _PositionType;
    amount: number;
}): {
    id: bigint;
    asset: Asset;
    createdAt: Time;
    positionType: PositionType;
    amount: number;
} {
    return {
        id: value.id,
        asset: value.asset,
        createdAt: value.createdAt,
        positionType: from_candid_PositionType_n6(_uploadFile, _downloadFile, value.positionType),
        amount: value.amount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    protocol: _Protocol;
    isLive: boolean;
}): {
    protocol: Protocol;
    isLive: boolean;
} {
    return {
        protocol: from_candid_Protocol_n10(_uploadFile, _downloadFile, value.protocol),
        isLive: value.isLive
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aave: null;
} | {
    compound: null;
}): Protocol {
    return "aave" in value ? Protocol.aave : "compound" in value ? Protocol.compound : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    borrow: null;
} | {
    deposit: null;
}): PositionType {
    return "borrow" in value ? PositionType.borrow : "deposit" in value ? PositionType.deposit : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Position>): Array<Position> {
    return value.map((x)=>from_candid_Position_n4(_uploadFile, _downloadFile, x));
}
function to_candid_MarketDataSource_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketDataSource): _MarketDataSource {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PositionType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionType): _PositionType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Protocol_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Protocol): _Protocol {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    protocol: Protocol;
    isLive: boolean;
}): {
    protocol: _Protocol;
    isLive: boolean;
} {
    return {
        protocol: to_candid_Protocol_n14(_uploadFile, _downloadFile, value.protocol),
        isLive: value.isLive
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Protocol): {
    aave: null;
} | {
    compound: null;
} {
    return value == Protocol.aave ? {
        aave: null
    } : value == Protocol.compound ? {
        compound: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionType): {
    borrow: null;
} | {
    deposit: null;
} {
    return value == PositionType.borrow ? {
        borrow: null
    } : value == PositionType.deposit ? {
        deposit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
